### ISSUE TITLE
Dynamic import of AppCookieBar causes build fail

### ISSUE THREAD

**Issue by vincentboiardt** [noaignite/create-ignite-app#43]
# Steps to reproduce:

- Clone directory
- `yarn && yarn build`

```$ next build
info  - Checking validity of types  
info  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /Users/vincent/Sites/create-ignite-app/babel.config.js
info  - Creating an optimized production build  
Failed to compile.

HookWebpackError: File /Users/vincent/Sites/create-ignite-app/.next/server/chunks/partials/AppCookieBar.js does not exist.
    at makeWebpackError (/Users/vincent/Sites/create-ignite-app/node_modules/next/dist/compiled/webpack/bundle5.js:47121:9)
    at /Users/vincent/Sites/create-ignite-app/node_modules/next/dist/compiled/webpack/bundle5.js:31041:12
    at eval (eval at create (/Users/vincent/Sites/create-ignite-app/node_modules/next/dist/compiled/webpack/bundle5.js:141201:10), <anonymous>:27:1)
    at /Users/vincent/Sites/create-ignite-app/node_modules/next/dist/compiled/webpack/bundle5.js:28494:26
    at /Users/vincent/Sites/create-ignite-app/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js:319:36
-- inner error --
Error: File /Users/vincent/Sites/create-ignite-app/.next/server/chunks/partials/AppCookieBar.js does not exist.
    at Job.emitDependency (/Users/vincent/Sites/create-ignite-app/node_modules/next/dist/compiled/@vercel/nft/index.js:1:86927)
    at async Promise.all (index 16)
    at async Object.nodeFileTrace (/Users/vincent/Sites/create-ignite-app/node_modules/next/dist/compiled/@vercel/nft/index.js:1:82679)
    at async /Users/vincent/Sites/create-ignite-app/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js:88:28
    at async Span.traceAsyncFn (/Users/vincent/Sites/create-ignite-app/node_modules/next/dist/trace/trace.js:74:20)
    at async TraceEntryPointsPlugin.createTraceAssets (/Users/vincent/Sites/create-ignite-app/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js:69:9)
caused by plugins in Compilation.hooks.processAssets
Error: File /Users/vincent/Sites/create-ignite-app/.next/server/chunks/partials/AppCookieBar.js does not exist.
    at Job.emitDependency (/Users/vincent/Sites/create-ignite-app/node_modules/next/dist/compiled/@vercel/nft/index.js:1:86927)
    at async Promise.all (index 16)
    at async Object.nodeFileTrace (/Users/vincent/Sites/create-ignite-app/node_modules/next/dist/compiled/@vercel/nft/index.js:1:82679)
    at async /Users/vincent/Sites/create-ignite-app/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js:88:28
    at async Span.traceAsyncFn (/Users/vincent/Sites/create-ignite-app/node_modules/next/dist/trace/trace.js:74:20)
    at async TraceEntryPointsPlugin.createTraceAssets (/Users/vincent/Sites/create-ignite-app/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js:69:9)


> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by vincentboiardt** [comment]
Created PR.

Looks like the webpackChunkName comment causes it, perhaps together with `ssr: false`.
